language: node_js
node_js:
- '10'
install:
- npm install
before_script:
- npm run coveralls
script:
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: F21vs6JlKAkvePXkvyv5g8N3+4gqSpAPMrBtHl7SjATKo4omxClhheyWPXvc4BAKVEfcQdDXtoG++mKvOChGo0EFK6XIDcycg1jL7RpD0z2g5zxwXIoae6lS/XvLmA+4J6QoigClGLv6Ix2m1wMHaP8e1W502Cv+6ZOULfvWtesdBahGJ/WkaxaksvRvcXX7ZgGwYpY9f0obuTfxXD79w7pKwe/9PJy40W3APbbE4l3Ccm0T0HPdCj6tWoCg6Zh8Y67GtNbl7ToMvEqclyN1zc+82i19qsxW1lApH+H5JgsGL0EtHIayFCibZb2ItakFDI8brxGwLMSoavXxi9w7c/W0LUdz5iLNqOshHEOtilVH+/BC9hwAqCaMPvK+q6z/bQH6hh+SdL66+u7NxTJBpWK/o0PLKhyI+bwks6+ltaWH/GAkCB1MVM8wNAz9H36zg/nsT/knj0l+s4oGQwnQWyJCEtCdCdFYPyBAptF3KFxENoNh0Ob/ejOKEzolbd0Zf7cKntyCVnYNvGVCTDoUmtTbHIbR98r2jrzmA4fQKgkewcJ/61zVfQQAB/XVAeM00A51sHSoottU8IDm7ws5GmhUn/zTp88OKPj8WilQJVtukV9ZSitDNbETo8TirH80HJYcLP8aH8iIymg/W74CUZWOB4geLn5ft3sd4mpD14M=
  secret_access_key:
    secure: gvQzUPFn6mn6CRwgpTYoxVhgH8ehiepiQddKVF/EGddubfTiwUcfnD4h7fEMZyxN1l9M0151ZqmIamRW8dXa+FJ5EQL1q1zLBGWKxAl9jA1xTEDN2eiUanAyv/vxoh1XZAHwDmiMqRD2+QgnEoIsNtF+iVu16VH4pfIeI6+6JtAfz8iuFiLsqHULGC1fTriRvrMRq30nR1Ajaik87OZ97eVOAlyFy7YStDzUfGaPwcl1ilmtx/wH0P53ucFB06B3squBeCg2aJ4I2dDhjhiLZjWSNyv7LCamh4/TFi89hO4V6l3zce7kftP9JstVSAYnlINjKzahqGa7j2cwoQWG4O/C51BJKgeGiWB8gBZj02/qHjzK+8yvz4fARdMAgHKcnJg1AN6IdgLHHcubO9QOw6JD3Gs3mFjlDrnv+9oAwKxKoY32QlpjUHALx98kPCzhvNlslx5eOd91AGatOUKiGN8r276pNP6QgUO9rDFZ/4kuSGlEXY4BUDPJFttTEM5oOUDqrS0IoTqjT6uvd3KYTfb6s7KP9q9rZG1lhdFmU8q16yhK8qRyupqzueCF1r/7dIX9mVDxG9aKuhInCq/71PUDBA+bCF9b0yyyN1UxE5cHcp8q0CKlCv31UgMxWiYEqDjnGuZSIzgO8BJunJGl2+pBJaMe166NDQomJjqlaw4=
  bucket: cv.potsides.com
  region: eu-west-2
  skip_cleanup: true
  local_dir: build
  upload-dir: cv
  acl: public_read
